import Head from 'next/head'

import { Inter } from 'next/font/google'
import { AiFillInstagram, AiFillLinkedin } from 'react-icons/ai'
import styles from '@/styles/Home.module.css'

import variables from '@/styles/variables.module.scss'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Pablo A</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={variables.box}>
          <img src="https://i.imgur.com/F4LUPrb.png" alt="Pablo A" className={variables.profileImage} />
          <div className={variables.cardSocial}>
            <div className={variables.title}>
              Pablo A. Borges
            </div>
          </div>
          <div className={variables.subtitle}>
            Software Engineer • CTO • Ethical hacker • Mentor
          </div>
            
          <div className={variables.cardSocial}>
            Conecte-se comigo: 
            <a href="https://www.linkedin.com/in/pabloa/" target="_blank" rel="noreferrer" className={variables.cardSocialLink}>
              LinkedIn
            </a> • 
            <a href="https://www.instagram.com/pabloaborges/" target="_blank" rel="noreferrer" className={variables.cardSocialLink}>
              Instagram
            </a>
          </div>
        </div>
        {/* <div className={variables.cardBox}>
          <img src="https://i.imgur.com/JgGV9nN.png" alt="Pablo A" className={variables.cardImage} />
        </div> */}
        <div className={variables.cardBoxNormal}>
          <img src="https://i.imgur.com/CRCmyJk.png" alt="Pablo A" className={variables.cardImageNormal} />
        </div>
        <div className={variables.cardBox}>
          <img src="https://i.imgur.com/D282Ft5.png" alt="Pablo A" className={variables.cardImage} />
        </div>
        <div className={variables.cardBoxNormal}>
          <img src="https://i.imgur.com/K4p2Ltz.png" alt="Pablo A" className={variables.cardImageNormal} />
        </div>
        <div className={variables.cardBoxNormal}>
          <img src="https://i.imgur.com/tWKSWMS.png" alt="Pablo A" className={variables.cardImageNormal} />
        </div>     
      </main>
    </>
  )
}
