import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

import variables from '@/styles/variables.module.scss'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Pablo A</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={variables.box}>
          <img src="https://i.imgur.com/F4LUPrb.png" alt="Pablo A" className={variables.profileImage} />
          <div className={variables.title}>
            Pablo A. Borges
          </div>
          <div className={variables.subtitle}>
            @pabloa
          </div>
        </div>
        <div className={variables.cardBox}>
          <img src="https://i.imgur.com/JgGV9nN.png" alt="Pablo A" className={variables.cardImage} />
        </div>
        <div className={variables.cardBox}>
          <img src="https://i.imgur.com/wmYv9V9.png" alt="Pablo A" className={variables.cardImage} />
        </div>
        <div className={variables.cardBox}>
          <img src="https://i.imgur.com/IuzacgI.png" alt="Pablo A" className={variables.cardImage} />
        </div>
        <div className={variables.cardBox}>
          <img src="https://i.imgur.com/EkQYuLP.png" alt="Pablo A" className={variables.cardImage} />
        </div>
        <div className={variables.cardBox}>
          <img src="https://i.imgur.com/uh8zRmr.png" alt="Pablo A" className={variables.cardImage} />
        </div>
      </main>
    </>
  )
}
